language: go
go:
  - 1.x
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - 1.10
  - 1.11
  - 1.12
  - 1.13
  - tip
before_install:
  - go get github.com/json-iterator/go
  - go get github.com/BurntSushi/toml
  - go get gopkg.in/yaml.v2